version: '3.8'

services:
  myweb:
    build: .
    container_name: personal-home
    ports:
      - "3456:3456"
    environment:
      - NODE_ENV=production
      - PORT=3456
      - HOST=0.0.0.0
    volumes:
      # RC 파일을 호스트와 공유 (데이터 영속성)
      - ./.myweb.rc:/app/.myweb.rc:rw
      # 홈 디렉토리의 RC 파일과 연결 (선택사항)
      - ${HOME}/.myweb.rc:/app/.myweb.rc:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3456/api/system', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myweb.rule=Host(`localhost`)"
      - "traefik.http.services.myweb.loadbalancer.server.port=3456"
